name: Hello world

on:
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello world"
      - name: List workspace files
        run: |
          echo "Workspace path: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE
